{
 "title": "Details",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "community_id",
    "query": "SELECT community_id_b64 FROM network_dpi"
   }
  ]
 },
 "panels": [
  {
   "type": "geomap",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "measurement": "flow",
     "query": "SELECT \"latitude\", \"longitude\" FROM \"flow\" WHERE (\"community_id\" =~ /^$community_id$/)  AND latitude!=0",
     "queryText": "SELECT \nCOUNT(id) as c,\njson_extract(enrichment, '$.geoip.country_name') as country\nFROM network_dpi \nWHERE \ncommunity_id_b64==${community_id:singlequote}\nAND timestamp >= $__from / 1000 and timestamp < $__to / 1000\nAND length(country)>1\nGROUP BY country\nORDER BY timestamp DESC;",
     "rawQueryText": "SELECT \nCOUNT(id) as c,\njson_extract(enrichment, '$.geoip.country_name') as country\nFROM network_dpi \nWHERE \ncommunity_id_b64==${community_id:singlequote}\nAND timestamp >= $__from / 1000 and timestamp < $__to / 1000\nAND length(country)>1\nGROUP BY country\nORDER BY timestamp DESC;",
     "select": [
      [
       { "params": [ "latitude" ], "type": "field" }
      ],
      [
       { "params": [ "longitude" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "community_id_b64", "operator": "=~", "value": "/^$community_id$/" }
     ],
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT COUNT(id) as c\nFROM network_alert\nWHERE \ncommunity_id_b64==${community_id:singlequote}\nAND timestamp >= $__from / 1000 and timestamp < $__to / 1000",
     "rawQueryText": "SELECT COUNT(id) as c\nFROM network_alert\nWHERE \ncommunity_id_b64==${community_id:singlequote}\nAND timestamp >= $__from / 1000 and timestamp < $__to / 1000",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Flows",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT COUNT(id) as c\nFROM network_dpi \nWHERE \ncommunity_id_b64==${community_id:singlequote}\nAND timestamp >= $__from / 1000 and timestamp < $__to / 1000",
     "rawQueryText": "SELECT COUNT(id) as c\nFROM network_dpi \nWHERE \ncommunity_id_b64==${community_id:singlequote}\nAND timestamp >= $__from / 1000 and timestamp < $__to / 1000"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "flow",
     "query": "SELECT \"bidirectional_duration_ms\" FROM \"flow\" WHERE (\"community_id\" =~ /^$community_id$/)",
     "queryText": "SELECT SUM(bidirectional_duration_ms) as c\nFROM network_dpi \nWHERE \ncommunity_id_b64==${community_id:singlequote}\nAND timestamp >= $__from / 1000 and timestamp < $__to / 1000",
     "rawQueryText": "SELECT SUM(bidirectional_duration_ms) as c\nFROM network_dpi \nWHERE \ncommunity_id_b64==${community_id:singlequote}\nAND timestamp >= $__from / 1000 and timestamp < $__to / 1000",
     "select": [
      [
       { "params": [ "bidirectional_duration_ms" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "community_id_b64", "operator": "=~", "value": "/^$community_id$/" }
     ],
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "I/O",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "flow",
     "query": "SELECT \"bidirectional_bytes\" FROM \"flow\" WHERE (\"community_id\" =~ /^$community_id$/)",
     "queryText": "SELECT SUM(bidirectional_bytes) as c\nFROM network_dpi \nWHERE \ncommunity_id_b64==${community_id:singlequote}\nAND timestamp >= $__from / 1000 and timestamp < $__to / 1000",
     "rawQueryText": "SELECT SUM(bidirectional_bytes) as c\nFROM network_dpi \nWHERE \ncommunity_id_b64==${community_id:singlequote}\nAND timestamp >= $__from / 1000 and timestamp < $__to / 1000",
     "select": [
      [
       { "params": [ "bidirectional_bytes" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "community_id_b64", "operator": "=~", "value": "/^$community_id$/" }
     ],
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "queryText": "SELECT \ntime as Time,\ncategory as Category,\nseverity as Severity,\njson_extract(enrichment, '$.geoip.country') as Country,\nsrc_ip as Source,\ndst_ip as Destination, \nsignature as Signature\nFROM network_alert \nWHERE \ncommunity_id_b64==${community_id:singlequote}\nAND timestamp >= $__from / 1000 and timestamp < $__to / 1000\nORDER BY timestamp DESC;",
     "rawQueryText": "SELECT \ntime as Time,\ncategory as Category,\nseverity as Severity,\njson_extract(enrichment, '$.geoip.country') as Country,\nsrc_ip as Source,\ndst_ip as Destination, \nsignature as Signature\nFROM network_alert \nWHERE \ncommunity_id_b64==${community_id:singlequote}\nAND timestamp >= $__from / 1000 and timestamp < $__to / 1000\nORDER BY timestamp DESC;"
    }
   ]
  },
  { "title": "Flows", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "measurement": "flow",
     "query": "SELECT \"application_category_name\" as \"Category\", \"application_name\" as \"Application\", \"src_ip\" as \"Source IP\", \"dst_ip\" as \"Destination IP\", \"requested_server_name\" as \"Domain\" FROM \"flow\" WHERE (\"community_id\" =~ /^$community_id$/)",
     "queryText": "SELECT \ntime as Time,\napplication_category_name as Category,\napplication_name as Application,\nrisk as Risk,\njson_extract(enrichment, '$.geoip.country') as Country,\nsrc_ip as Source,\ndst_ip as Destination, \nrequested_server_name as Server,\nbidirectional_bytes as \"I/O\"\nFROM network_dpi \nWHERE \ncommunity_id_b64==${community_id:singlequote}\nAND timestamp >= $__from / 1000 and timestamp < $__to / 1000\nORDER BY timestamp DESC;",
     "rawQueryText": "SELECT \ntime as Time,\napplication_category_name as Category,\napplication_name as Application,\nrisk as Risk,\njson_extract(enrichment, '$.geoip.country') as Country,\nsrc_ip as Source,\ndst_ip as Destination, \nrequested_server_name as Server,\nbidirectional_bytes as \"I/O\"\nFROM network_dpi \nWHERE \ncommunity_id_b64==${community_id:singlequote}\nAND timestamp >= $__from / 1000 and timestamp < $__to / 1000\nORDER BY timestamp DESC;",
     "select": [
      [
       { "params": [ "application_category_name" ], "type": "field" },
       { "params": [ "Category" ], "type": "alias" }
      ],
      [
       { "params": [ "application_name" ], "type": "field" },
       { "params": [ "Application" ], "type": "alias" }
      ],
      [
       { "params": [ "src_ip" ], "type": "field" },
       { "params": [ "Source IP" ], "type": "alias" }
      ],
      [
       { "params": [ "dst_ip" ], "type": "field" },
       { "params": [ "Destination IP" ], "type": "alias" }
      ],
      [
       { "params": [ "requested_server_name" ], "type": "field" },
       { "params": [ "Domain" ], "type": "alias" }
      ],
      [
       { "params": [ "src_port" ], "type": "field" },
       { "params": [ "Source port" ], "type": "alias" }
      ],
      [
       { "params": [ "dst_port" ], "type": "field" },
       { "params": [ "Destination port" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "community_id_b64", "operator": "=~", "value": "/^$community_id$/" }
     ],
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}