{
 "title": "PiRogue",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "client_ip",
    "label": "Device",
    "query": "SELECT DISTINCT(src_ip) as device FROM network_dpi WHERE application_name==\"DNS\" AND timestamp >= $__from / 1000 and timestamp < $__to / 1000"
   }
  ]
 },
 "panels": [
  {
   "type": "geomap",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "flow",
     "query": "SELECT \"latitude\", \"longitude\" FROM \"flows_5d\".\"flow\" WHERE (\"src_ip\" =~ /^$client_ip$/ OR \"dst_ip\" =~ /^$client_ip$/) AND $timeFilter AND latitude!=0",
     "queryText": "SELECT \n100.0*SUM(bidirectional_bytes)/(\n  SELECT 1.0*SUM(bidirectional_bytes)\n  FROM network_dpi \n  WHERE \n  (\n    src_ip IN (${client_ip:singlequote})\n    OR\n    dst_ip IN (${client_ip:singlequote})\n  )\n  AND length(json_extract(enrichment, '$.geoip.country_name'))>0\n  AND timestamp >= $__from / 1000 and timestamp < $__to / 1000\n  ) as weight,\njson_extract(enrichment, '$.geoip.country_name') as country\nFROM network_dpi \nWHERE \n(\n  src_ip IN (${client_ip:singlequote})\n  OR\n  dst_ip IN (${client_ip:singlequote})\n)\nAND length(country)>1\nAND timestamp >= $__from / 1000 and timestamp < $__to / 1000\nGROUP BY country",
     "rawQueryText": "SELECT \n100.0*SUM(bidirectional_bytes)/(\n  SELECT 1.0*SUM(bidirectional_bytes)\n  FROM network_dpi \n  WHERE \n  (\n    src_ip IN (${client_ip:singlequote})\n    OR\n    dst_ip IN (${client_ip:singlequote})\n  )\n  AND length(json_extract(enrichment, '$.geoip.country_name'))>0\n  AND timestamp >= $__from / 1000 and timestamp < $__to / 1000\n  ) as weight,\njson_extract(enrichment, '$.geoip.country_name') as country\nFROM network_dpi \nWHERE \n(\n  src_ip IN (${client_ip:singlequote})\n  OR\n  dst_ip IN (${client_ip:singlequote})\n)\nAND length(country)>1\nAND timestamp >= $__from / 1000 and timestamp < $__to / 1000\nGROUP BY country",
     "select": [
      [
       { "params": [ "latitude" ], "type": "field" }
      ],
      [
       { "params": [ "longitude" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "src_ip", "operator": "=~", "value": "/^$client_ip$/" },
      { "condition": "OR", "key": "dst_ip", "operator": "=~", "value": "/^$client_ip$/" }
     ]
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT COUNT(id) as c\nFROM network_alert\nWHERE \n(\n  src_ip IN (${client_ip:singlequote})\n  OR\n  dst_ip IN (${client_ip:singlequote})\n)\nAND timestamp >= $__from / 1000 and timestamp < $__to / 1000",
     "rawQueryText": "SELECT COUNT(id) as c\nFROM network_alert\nWHERE \n(\n  src_ip IN (${client_ip:singlequote})\n  OR\n  dst_ip IN (${client_ip:singlequote})\n)\nAND timestamp >= $__from / 1000 and timestamp < $__to / 1000",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Devices",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "flow",
     "query": "SELECT count(distinct(\"src_ip\")) FROM \"flow\" WHERE (\"application_name\" =~ /^DNS/) AND $timeFilter",
     "queryText": "SELECT COUNT(DISTINCT(src_ip)) FROM network_dpi WHERE application_name==\"DNS\" AND timestamp >= $__from / 1000 and timestamp < $__to / 1000",
     "rawQueryText": "SELECT COUNT(DISTINCT(src_ip)) FROM network_dpi WHERE application_name==\"DNS\" AND timestamp >= $__from / 1000 and timestamp < $__to / 1000",
     "select": [
      [
       { "params": [ "src_ip" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "application_name", "operator": "=~", "value": "/^DNS/" }
     ]
    }
   ]
  },
  {
   "title": "Flows",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "flow",
     "queryText": "SELECT COUNT(id) as c\nFROM network_dpi \nWHERE \n(\n  src_ip IN (${client_ip:singlequote})\n  OR\n  dst_ip IN (${client_ip:singlequote})\n)\nAND timestamp >= $__from / 1000 and timestamp < $__to / 1000",
     "rawQueryText": "SELECT COUNT(id) as c\nFROM network_dpi \nWHERE \n(\n  src_ip IN (${client_ip:singlequote})\n  OR\n  dst_ip IN (${client_ip:singlequote})\n)\nAND timestamp >= $__from / 1000 and timestamp < $__to / 1000",
     "select": [
      [
       { "params": [ "bidirectional_duration_ms" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "src_ip", "operator": "=~", "value": "/^$client_ip$/" },
      { "condition": "OR", "key": "dst_ip", "operator": "=~", "value": "/^$client_ip$/" }
     ]
    }
   ]
  },
  {
   "title": "Domains",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "flow",
     "queryText": "SELECT COUNT(DISTINCT(requested_server_name)) as c\nFROM network_dpi \nWHERE \n(\n  src_ip IN (${client_ip:singlequote})\n  OR\n  dst_ip IN (${client_ip:singlequote})\n)\nAND timestamp >= $__from / 1000 and timestamp < $__to / 1000",
     "rawQueryText": "SELECT COUNT(DISTINCT(requested_server_name)) as c\nFROM network_dpi \nWHERE \n(\n  src_ip IN (${client_ip:singlequote})\n  OR\n  dst_ip IN (${client_ip:singlequote})\n)\nAND timestamp >= $__from / 1000 and timestamp < $__to / 1000",
     "select": [
      [
       { "params": [ "requested_server_name" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "src_ip", "operator": "=~", "value": "/^$client_ip$/" },
      { "condition": "OR", "key": "dst_ip", "operator": "=~", "value": "/^$client_ip$/" }
     ],
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "I/O",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "measurement": "flow",
     "queryText": "SELECT \nSUM(bidirectional_bytes) as \"I/O\"\nFROM network_dpi \nWHERE \n(\n  src_ip IN (${client_ip:singlequote})\n  OR\n  dst_ip IN (${client_ip:singlequote})\n)\nAND timestamp >= $__from / 1000 and timestamp < $__to / 1000",
     "rawQueryText": "SELECT \nSUM(bidirectional_bytes) as \"I/O\"\nFROM network_dpi \nWHERE \n(\n  src_ip IN (${client_ip:singlequote})\n  OR\n  dst_ip IN (${client_ip:singlequote})\n)\nAND timestamp >= $__from / 1000 and timestamp < $__to / 1000",
     "select": [
      [
       { "params": [ "bidirectional_bytes" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "src_ip", "operator": "=~", "value": "/^$client_ip$/" },
      { "condition": "OR", "key": "dst_ip", "operator": "=~", "value": "/^$client_ip$/" }
     ],
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "I/O",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "flow",
     "queryText": "SELECT \ntime,\n(bidirectional_bytes/((bidirectional_duration_ms+1)/1000.0)) as \"I/O\"\nFROM network_dpi \nWHERE \n(\n  src_ip IN (${client_ip:singlequote})\n  OR\n  dst_ip IN (${client_ip:singlequote})\n)\nAND timestamp >= $__from / 1000 and timestamp < $__to / 1000\nORDER BY timestamp DESC;",
     "rawQueryText": "SELECT \ntime,\n(bidirectional_bytes/((bidirectional_duration_ms+1)/1000.0)) as \"I/O\"\nFROM network_dpi \nWHERE \n(\n  src_ip IN (${client_ip:singlequote})\n  OR\n  dst_ip IN (${client_ip:singlequote})\n)\nAND timestamp >= $__from / 1000 and timestamp < $__to / 1000\nORDER BY timestamp DESC;",
     "select": [
      [
       { "params": [ "bidirectional_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "src_ip", "operator": "=~", "value": "/^$client_ip$/" },
      { "condition": "OR", "key": "dst_ip", "operator": "=~", "value": "/^$client_ip$/" }
     ]
    }
   ]
  },
  {
   "title": "Security alerts",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "queryText": "SELECT \ntime as Time,\ncategory as Category,\nseverity as Severity,\njson_extract(enrichment, '$.geoip.country') as Country,\nsrc_ip as Source,\ndst_ip as Destination, \nsignature as Signature,\ncommunity_id_b64 as CID\nFROM network_alert \nWHERE \n(\n  src_ip IN (${client_ip:singlequote})\n  OR\n  dst_ip IN (${client_ip:singlequote})\n)\nAND timestamp >= $__from / 1000 and timestamp < $__to / 1000\nORDER BY timestamp DESC;",
     "rawQueryText": "SELECT \ntime as Time,\ncategory as Category,\nseverity as Severity,\njson_extract(enrichment, '$.geoip.country') as Country,\nsrc_ip as Source,\ndst_ip as Destination, \nsignature as Signature,\ncommunity_id_b64 as CID\nFROM network_alert \nWHERE \n(\n  src_ip IN (${client_ip:singlequote})\n  OR\n  dst_ip IN (${client_ip:singlequote})\n)\nAND timestamp >= $__from / 1000 and timestamp < $__to / 1000\nORDER BY timestamp DESC;"
    }
   ]
  },
  {
   "title": "Flows",
   "type": "table",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "measurement": "flow",
     "query": "SELECT \"application_category_name\" AS \"Category\", \"application_name\" AS \"Application\", \"requested_server_name\" AS \"Domain\", \"src_ip\" AS \"Source IP\", \"dst_ip\" AS \"Destination IP\", \"country_iso\" AS \"Country\", \"bidirectional_bytes\" AS \"I/O\", \"community_id_b64\" FROM \"flow\" WHERE (\"src_ip\" =~ /^$client_ip$/ OR \"dst_ip\" =~ /^$client_ip$/) AND $timeFilter ORDER BY time DESC",
     "queryText": "SELECT \ntime as Time,\napplication_category_name as Category,\napplication_name as Application,\nrisk as Risk,\njson_extract(enrichment, '$.geoip.country') as Country,\njson_extract(enrichment, '$.src_hostname') as \"Src hostname\",\nsrc_ip as Source,\njson_extract(enrichment, '$.dst_hostname') as \"Dst hostname\",\ndst_ip as Destination, \nrequested_server_name as Request,\nbidirectional_bytes as \"I/O\",\ncommunity_id_b64 as CID\nFROM network_dpi \nWHERE \n(\n  src_ip IN (${client_ip:singlequote})\n  OR\n  dst_ip IN (${client_ip:singlequote})\n)\nAND timestamp >= $__from / 1000 and timestamp < $__to / 1000\nORDER BY timestamp DESC;",
     "rawQueryText": "SELECT \ntime as Time,\napplication_category_name as Category,\napplication_name as Application,\nrisk as Risk,\njson_extract(enrichment, '$.geoip.country') as Country,\njson_extract(enrichment, '$.src_hostname') as \"Src hostname\",\nsrc_ip as Source,\njson_extract(enrichment, '$.dst_hostname') as \"Dst hostname\",\ndst_ip as Destination, \nrequested_server_name as Request,\nbidirectional_bytes as \"I/O\",\ncommunity_id_b64 as CID\nFROM network_dpi \nWHERE \n(\n  src_ip IN (${client_ip:singlequote})\n  OR\n  dst_ip IN (${client_ip:singlequote})\n)\nAND timestamp >= $__from / 1000 and timestamp < $__to / 1000\nORDER BY timestamp DESC;",
     "select": [
      [
       { "params": [ "application_category_name" ], "type": "field" }
      ],
      [
       { "params": [ "application_name" ], "type": "field" }
      ],
      [
       { "params": [ "requested_server_name" ], "type": "field" }
      ],
      [
       { "params": [ "src_ip" ], "type": "field" }
      ],
      [
       { "params": [ "dst_ip" ], "type": "field" }
      ],
      [
       { "params": [ "country_iso" ], "type": "field" }
      ],
      [
       { "params": [ "bidirectional_bytes" ], "type": "field" }
      ],
      [
       { "params": [ "bidirectional_bytes" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "src_ip", "operator": "=~", "value": "/^$client_ip$/" },
      { "condition": "OR", "key": "dst_ip", "operator": "=~", "value": "/^$client_ip$/" }
     ]
    }
   ]
  }
 ]
}