#!/bin/sh

set -e

# Install grafana configuration
if ! cmp -s /usr/share/pirogue/grafana/grafana.ini /etc/grafana/grafana.ini; then
   cp /usr/share/pirogue/grafana/grafana.ini /etc/grafana/grafana.ini
   
   deb-systemd-invoke enable grafana-server
   deb-systemd-invoke restart grafana-server
fi

# Install required grafana plugins
grafana-cli plugins install grafana-worldmap-panel
deb-systemd-invoke restart grafana-server
