{
 "title": "Home",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "client_ip",
    "label": "Device",
    "query": "SELECT \"src_ip\" FROM \"flow\" WHERE (\"application_name\" =~ /DNS/) "
   }
  ]
 },
 "panels": [
  {
   "title": "Devices",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "flow",
     "query": "SELECT count(distinct(\"src_ip\")) FROM \"flow\" WHERE (\"application_name\" =~ /^DNS/) AND $timeFilter",
     "select": [
      [
       { "params": [ "src_ip" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "application_name", "operator": "=~", "value": "/^DNS/" }
     ]
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "alert",
     "query": "SELECT count(\"alert_gid\") FROM \"alert\" WHERE (\"src_ip\" =~ /^$client_ip$/ OR \"dest_ip\" =~ /^$client_ip$/) AND $timeFilter AND \"alert_severity\" < 3",
     "select": [
      [
       { "params": [ "alert_gid" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "src_ip", "operator": "=~", "value": "/^$client_ip$/" },
      { "condition": "OR", "key": "dest_ip", "operator": "=~", "value": "/^$client_ip$/" }
     ]
    }
   ]
  },
  {
   "title": "I/O",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "measurement": "flow",
     "select": [
      [
       { "params": [ "bidirectional_bytes" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "src_ip", "operator": "=~", "value": "/^$client_ip$/" },
      { "condition": "OR", "key": "dst_ip", "operator": "=~", "value": "/^$client_ip$/" }
     ]
    }
   ]
  },
  {
   "title": "Flows",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "measurement": "flow",
     "select": [
      [
       { "params": [ "bidirectional_duration_ms" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "src_ip", "operator": "=~", "value": "/^$client_ip$/" },
      { "condition": "OR", "key": "dst_ip", "operator": "=~", "value": "/^$client_ip$/" }
     ]
    }
   ]
  },
  {
   "title": "Domains",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "flow",
     "select": [
      [
       { "params": [ "requested_server_name" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "src_ip", "operator": "=~", "value": "/^$client_ip$/" },
      { "condition": "OR", "key": "dst_ip", "operator": "=~", "value": "/^$client_ip$/" }
     ]
    }
   ]
  },
  {
   "title": "I/O",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "flow",
     "select": [
      [
       { "params": [ "bidirectional_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "src_ip", "operator": "=~", "value": "/^$client_ip$/" },
      { "condition": "OR", "key": "dst_ip", "operator": "=~", "value": "/^$client_ip$/" }
     ]
    }
   ]
  },
  {
   "title": "Servers location",
   "type": "geomap",
   "gridPos": { "h": 11, "w": 15, "x": 0, "y": 4 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "flow",
     "query": "SELECT \"latitude\", \"longitude\" FROM \"flows_5d\".\"flow\" WHERE (\"src_ip\" =~ /^$client_ip$/ OR \"dst_ip\" =~ /^$client_ip$/) AND $timeFilter AND latitude!=0",
     "select": [
      [
       { "params": [ "latitude" ], "type": "field" }
      ],
      [
       { "params": [ "longitude" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "src_ip", "operator": "=~", "value": "/^$client_ip$/" },
      { "condition": "OR", "key": "dst_ip", "operator": "=~", "value": "/^$client_ip$/" }
     ]
    }
   ]
  },
  {
   "title": "Flows per country",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 4 },
   "targets": [
    {
     "measurement": "flow",
     "query": "SELECT distinct(country_iso), sum(bidirectional_bytes) FROM \"flow\" WHERE $timeFilter GROUP BY country_iso",
     "select": [
      [
       { "params": [ "country" ], "type": "field" }
      ],
      [
       { "params": [ "bidirectional_bytes" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "src_ip", "operator": "=~", "value": "/^$client_ip$/" },
      { "condition": "OR", "key": "dst_ip", "operator": "=~", "value": "/^$client_ip$/" }
     ]
    }
   ]
  },
  {
   "title": "Alert timeline",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 9, "x": 15, "y": 12 },
   "targets": [
    {
     "measurement": "alert",
     "query": "SELECT \"alert_severity\", \"alert_signature\" FROM \"alert\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "alert_severity" ], "type": "field" }
      ],
      [
       { "params": [ "alert_signature" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "src_ip", "operator": "=~", "value": "/^$client_ip$/" },
      { "condition": "OR", "key": "dest_ip", "operator": "=~", "value": "/^$client_ip$/" }
     ]
    }
   ]
  },
  {
   "title": "Flows",
   "type": "table",
   "gridPos": { "h": 20, "w": 15, "x": 0, "y": 15 },
   "targets": [
    {
     "measurement": "flow",
     "query": "SELECT \"application_category_name\" AS \"Category\", \"application_name\" AS \"Application\", \"requested_server_name\" AS \"Domain\", \"src_ip\" AS \"Source IP\", \"dst_ip\" AS \"Destination IP\", \"country_iso\" AS \"Country\", \"bidirectional_bytes\" AS \"I/O\", \"community_id_b64\" FROM \"flow\" WHERE (\"src_ip\" =~ /^$client_ip$/ OR \"dst_ip\" =~ /^$client_ip$/) AND $timeFilter ORDER BY time DESC",
     "select": [
      [
       { "params": [ "application_category_name" ], "type": "field" }
      ],
      [
       { "params": [ "application_name" ], "type": "field" }
      ],
      [
       { "params": [ "requested_server_name" ], "type": "field" }
      ],
      [
       { "params": [ "src_ip" ], "type": "field" }
      ],
      [
       { "params": [ "dst_ip" ], "type": "field" }
      ],
      [
       { "params": [ "country_iso" ], "type": "field" }
      ],
      [
       { "params": [ "bidirectional_bytes" ], "type": "field" }
      ],
      [
       { "params": [ "bidirectional_bytes" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "src_ip", "operator": "=~", "value": "/^$client_ip$/" },
      { "condition": "OR", "key": "dst_ip", "operator": "=~", "value": "/^$client_ip$/" }
     ]
    }
   ]
  },
  {
   "title": "Suricata alerts",
   "type": "table",
   "gridPos": { "h": 20, "w": 9, "x": 15, "y": 15 },
   "targets": [
    {
     "measurement": "alert",
     "query": "SELECT \"alert_severity\" AS \"Severity\", \"alert_category\" AS \"Category\", \"alert_signature\" AS \"Rule\", \"src_ip\" AS \"Source IP\", \"dest_ip\" AS \"Destination IP\", \"community_id_b64\" FROM \"alert\" WHERE (\"src_ip\" =~ /^$client_ip$/ OR \"dest_ip\" =~ /^$client_ip$/) AND $timeFilter ORDER BY time DESC",
     "select": [
      [
       { "params": [ "alert_severity" ], "type": "field" },
       { "params": [ "Severity" ], "type": "alias" }
      ],
      [
       { "params": [ "alert_category" ], "type": "field" },
       { "params": [ "Category" ], "type": "alias" }
      ],
      [
       { "params": [ "alert_signature" ], "type": "field" },
       { "params": [ "Rule" ], "type": "alias" }
      ],
      [
       { "params": [ "community_id" ], "type": "field" }
      ],
      [
       { "params": [ "community_id" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "src_ip", "operator": "=~", "value": "/^$client_ip$/" },
      { "condition": "OR", "key": "dest_ip", "operator": "=~", "value": "/^$client_ip$/" }
     ]
    }
   ]
  }
 ]
}