{
 "title": "Flow details",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "community_id",
    "query": "SELECT \"community_id_b64\", \"bidirectional_bytes\" FROM \"flow\""
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "Community ID: `${community_id}`"
   }
  },
  {
   "title": "Flows",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "measurement": "flow",
     "query": "SELECT \"value\" FROM \"flow\" WHERE (\"community_id\" =~ /^$community_id$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "community_id_b64", "operator": "=~", "value": "/^$community_id$/" }
     ]
    }
   ]
  },
  {
   "title": "I/O bytes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "measurement": "flow",
     "query": "SELECT \"bidirectional_bytes\" FROM \"flow\" WHERE (\"community_id\" =~ /^$community_id$/)",
     "select": [
      [
       { "params": [ "bidirectional_bytes" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "community_id_b64", "operator": "=~", "value": "/^$community_id$/" }
     ]
    }
   ]
  },
  {
   "title": "Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "measurement": "flow",
     "query": "SELECT \"bidirectional_duration_ms\" FROM \"flow\" WHERE (\"community_id\" =~ /^$community_id$/)",
     "select": [
      [
       { "params": [ "bidirectional_duration_ms" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "community_id_b64", "operator": "=~", "value": "/^$community_id$/" }
     ]
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "measurement": "alert",
     "query": "SELECT \"value\" FROM \"alert\" WHERE (\"community_id_b64\" =~ /^$community_id$/) AND $timeFilter AND \"alert_severity\" < 3",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "community_id_b64", "operator": "=~", "value": "/^$community_id$/" }
     ]
    }
   ]
  },
  {
   "type": "geomap",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 2 },
   "targets": [
    {
     "measurement": "flow",
     "query": "SELECT \"latitude\", \"longitude\" FROM \"flow\" WHERE (\"community_id\" =~ /^$community_id$/)  AND latitude!=0",
     "select": [
      [
       { "params": [ "latitude" ], "type": "field" }
      ],
      [
       { "params": [ "longitude" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "community_id_b64", "operator": "=~", "value": "/^$community_id$/" }
     ]
    }
   ]
  },
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "measurement": "alert",
     "query": "SELECT \"alert_category\" AS \"Category\", \"alert_signature\" AS \"Rule\", \"alert_severity\" AS \"Sev.\", \"app_proto\" AS \"Proto\", \"src_ip\" AS \"Source IP\", \"src_port\" AS \"port\", \"dest_ip\" AS \"Destination IP\", \"dest_port\" AS \"port\" FROM \"alert\" WHERE (\"community_id\" =~ /^$community_id$/) ",
     "select": [
      [
       { "params": [ "alert_category" ], "type": "field" },
       { "params": [ "Category" ], "type": "alias" }
      ],
      [
       { "params": [ "alert_signature" ], "type": "field" },
       { "params": [ "Rule" ], "type": "alias" }
      ],
      [
       { "params": [ "alert_severity" ], "type": "field" },
       { "params": [ "Sev." ], "type": "alias" }
      ],
      [
       { "params": [ "app_proto" ], "type": "field" },
       { "params": [ "Proto" ], "type": "alias" }
      ],
      [
       { "params": [ "src_ip" ], "type": "field" },
       { "params": [ "Source IP" ], "type": "alias" }
      ],
      [
       { "params": [ "src_port" ], "type": "field" },
       { "params": [ "port" ], "type": "alias" }
      ],
      [
       { "params": [ "dest_ip" ], "type": "field" },
       { "params": [ "Destination IP" ], "type": "alias" }
      ],
      [
       { "params": [ "dest_port" ], "type": "field" },
       { "params": [ "port" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "community_id_b64", "operator": "=~", "value": "/^$community_id$/" }
     ]
    }
   ]
  },
  { "title": "Flows", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "measurement": "flow",
     "query": "SELECT \"application_category_name\" as \"Category\", \"application_name\" as \"Application\", \"src_ip\" as \"Source IP\", \"dst_ip\" as \"Destination IP\", \"requested_server_name\" as \"Domain\" FROM \"flow\" WHERE (\"community_id\" =~ /^$community_id$/)",
     "select": [
      [
       { "params": [ "application_category_name" ], "type": "field" },
       { "params": [ "Category" ], "type": "alias" }
      ],
      [
       { "params": [ "application_name" ], "type": "field" },
       { "params": [ "Application" ], "type": "alias" }
      ],
      [
       { "params": [ "src_ip" ], "type": "field" },
       { "params": [ "Source IP" ], "type": "alias" }
      ],
      [
       { "params": [ "dst_ip" ], "type": "field" },
       { "params": [ "Destination IP" ], "type": "alias" }
      ],
      [
       { "params": [ "requested_server_name" ], "type": "field" },
       { "params": [ "Domain" ], "type": "alias" }
      ],
      [
       { "params": [ "src_port" ], "type": "field" },
       { "params": [ "Source port" ], "type": "alias" }
      ],
      [
       { "params": [ "dst_port" ], "type": "field" },
       { "params": [ "Destination port" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "community_id_b64", "operator": "=~", "value": "/^$community_id$/" }
     ]
    }
   ]
  }
 ]
}